let Strip = neopixel.create(DigitalPin.P16, 4, NeoPixelMode.RGB)
Strip.clear()
Strip.clear()
basic.showIcon(IconNames.Yes)
basic.forever(function () {
    Strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Red))
    Strip.show()
    Strip.clear()
    basic.pause(1000)
    Strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Yellow))
    Strip.show()
    Strip.clear()
    basic.pause(1000)
    Strip.setPixelColor(2, neopixel.colors(NeoPixelColors.Green))
    Strip.show()
    Strip.clear()
    basic.pause(1000)
})
